// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFeGwxEX2g-98bKXFgCUAbOkpcnQxHFYc',
    appId: '1:634025178061:web:3e47d076d532ec2c2e4a84',
    messagingSenderId: '634025178061',
    projectId: 'chat-me-2383b',
    authDomain: 'chat-me-2383b.firebaseapp.com',
    storageBucket: 'chat-me-2383b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqnDgOM_A908MM9bpPMXLyfwVBksOttM',
    appId: '1:634025178061:android:472c57910a855c472e4a84',
    messagingSenderId: '634025178061',
    projectId: 'chat-me-2383b',
    storageBucket: 'chat-me-2383b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCIlXz7H7o4Mu06ci9_3_tJ5l6iDFCDY',
    appId: '1:634025178061:ios:1a4af067a48a3a382e4a84',
    messagingSenderId: '634025178061',
    projectId: 'chat-me-2383b',
    storageBucket: 'chat-me-2383b.firebasestorage.app',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCIlXz7H7o4Mu06ci9_3_tJ5l6iDFCDY',
    appId: '1:634025178061:ios:1a4af067a48a3a382e4a84',
    messagingSenderId: '634025178061',
    projectId: 'chat-me-2383b',
    storageBucket: 'chat-me-2383b.firebasestorage.app',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFeGwxEX2g-98bKXFgCUAbOkpcnQxHFYc',
    appId: '1:634025178061:web:6f2def1329ffda572e4a84',
    messagingSenderId: '634025178061',
    projectId: 'chat-me-2383b',
    authDomain: 'chat-me-2383b.firebaseapp.com',
    storageBucket: 'chat-me-2383b.firebasestorage.app',
  );
}
